publicHoistPattern:
  - vitest
  - vite-node

shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@commitlint/cli': ^20.5.3
    '@commitlint/config-conventional': ^20.5.3
    bumpp: ^10.4.1
    eslint: ^9.39.5
    husky: ^9.1.7
    lint-staged: ^16.4.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
  integrations:
    rabbitmq-client: ^5.0.8
  test:
    '@vitest/browser-playwright': ^4.1.11
    '@vitest/coverage-v8': ^4.1.11
    playwright: ^1.63.0
    vitest: ^4.1.11
  types:
    '@types/node': ^25.9.5

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

sideEffectsCache: false
strictPeerDependencies: false
