publicHoistPattern:
  - vitest
  - vite-node

shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.4.3
    '@commitlint/cli': ^20.4.2
    '@commitlint/config-conventional': ^20.4.2
    bumpp: ^11.1.0
    eslint: ^9.39.3
    husky: ^9.1.7
    lint-staged: ^16.2.7
    typescript: ^5.9.3
    unbuild: ^3.6.1
  integrations:
    rabbitmq-client: ^5.0.8
  test:
    '@vitest/browser-playwright': ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    playwright: ^1.58.2
    vitest: ^4.0.18
  types:
    '@types/node': ^25.3.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

sideEffectsCache: false
strictPeerDependencies: false
